services:
#  chroma:
#    container_name: maeve-chroma
#    image: chromadb/chroma
#    volumes:
#      - chroma_data:/data
#    ports:
#      - "8000:8000"
#  redis:
#    container_name: maeve-redis
#    image: redis:latest
#    volumes:
#      - redis_data:/data
#    ports:
#      - "6380:6379"
#  rag-ingester:
#    container_name: maeve-rag-ingester
#    image: rag-ingester
#    build:
#      context: rag-ingester
#      dockerfile: Dockerfile
#    environment:
#      MAEVE_HOST: "host.docker.internal:5284"
#    ports:
#      - "8001:80"
#    depends_on:
#      - chroma
#      - redis
#  rag-mcp-server:
#    container_name: maeve-rag-mcp-server
#    image: rag-mcp-server
#    build:
#      context: mcp-servers/rag-mcp-server
#      dockerfile: Dockerfile
  finch-mcp-server:
    container_name: finch-mcp-server
    image: finch-mcp-server
    ports:
      - "8018:8018"
    build:
      context: mcp-servers/FinchMCPServer
      dockerfile: Dockerfile
  hue-mcp-server:
    container_name: hue-mcp-server
    image: hue-mcp-server
    ports:
      - "8023:8023"
    volumes:
      - type: bind
        source: ./mcp-servers/hue-mcp/config.json
        target: /root/.hue-mcp/config.json
    build:
      context: mcp-servers/hue-mcp
      dockerfile: Dockerfile
#volumes:
#  chroma_data:
#  redis_data: