// <auto-generated />
using System;
using Maeve.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Maeve.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250726115405_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Maeve.Database.Document", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("documents");
                });

            modelBuilder.Entity("Maeve.Database.Message", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Thoughts")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("Maeve.Database.Message", b =>
                {
                    b.OwnsMany("Maeve.Database.Tool", "Tools", b1 =>
                        {
                            b1.Property<string>("MessageId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Function")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("MessageId", "__synthesizedOrdinal");

                            b1.ToTable("messages");

                            b1.ToJson("Tools");

                            b1.WithOwner()
                                .HasForeignKey("MessageId");

                            b1.OwnsMany("Maeve.Database.Tool+Argument", "Arguments", b2 =>
                                {
                                    b2.Property<string>("ToolMessageId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Tool__synthesizedOrdinal")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Key")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Value")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("ToolMessageId", "Tool__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("messages");

                                    b2.WithOwner()
                                        .HasForeignKey("ToolMessageId", "Tool__synthesizedOrdinal");
                                });

                            b1.Navigation("Arguments");
                        });

                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
